version: '3'
services:
  bae-backend:
    build: .
    container_name: emp-backend
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - ./.env
    volumes:
      - '.:/emp-erp-backend'
    links:
      - "emp-db"
#hostname
  emp-db:
    image: postgres
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - emp-db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    # environment:

    env_file:
      - ./.env
    ports:
      - "5000:80"
    links:
      - "emp-db"
volumes:
  emp-db:
  emp-backend: